class OneDriveConstants(object):
    UPLOAD_URL = "uploadUrl"
    CREATE_UPLOAD_SESSION = "createUploadSession"
    VALUE_CONTAINER = "value"
    ITEM = "item"
    DESCRIPTION = "description"
    ROOT = "root"
    FOLDER = "folder"
    SIZE = "size"
    FILE = "file"
    ID = "id"
    NAME = "name"
    LAST_MODIFIED = "lastModifiedDateTime"
    TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
